services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: coffee_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  web:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/coffee_db
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_BACKEND_URL: redis://redis:6379/1
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  celery_worker:
    build: .
    command: celery -A app.core.celery_app.celery worker -l info
    volumes:
      - .:/app
    depends_on:
      - redis
      - db

  celery_beat:
    build: .
    command: celery -A app.core.celery_app.celery beat -l info
    volumes:
      - .:/app
    depends_on:
      - redis
      - db

volumes:
  pg_data:
